### ISSUE TITLE
Mandrill configured, attempts to use Mailgun

### ISSUE THREAD

**Issue by astronouth7303** [anymail/django-anymail#113]
```
>>> from django.core.mail import send_mail
>>> send_mail('Test', 'This is a test email', 'noreply@<redacted>', ['webmaster@astro73.com'], fail_silently=False)
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/anymail/utils.py", line 366, in get_anymail_setting
    return settings.ANYMAIL[setting]
KeyError: 'MAILGUN_API_KEY'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/anymail/utils.py", line 369, in get_anymail_setting
    return getattr(settings, anymail_setting)
  File "/usr/local/lib/python3.5/dist-packages/django/conf/__init__.py", line 58, in __getattr__
    val = getattr(self._wrapped, name)
AttributeError: 'Settings' object has no attribute 'ANYMAIL_MAILGUN_API_KEY'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.5/code.py", line 91, in runcode
    exec(code, self.locals)
  File "<console>", line 1, in <module>
  File "/usr/local/lib/python3.5/dist-packages/django/core/mail/__init__.py", line 54, in send_mail
    fail_silently=fail_silently,
  File "/usr/local/lib/python3.5/dist-packages/django/core/mail/__init__.py", line 35, in get_connection
    return klass(fail_silently=fail_silently, **kwds)
  File "/usr/local/lib/python3.5/dist-packages/anymail/backends/mailgun.py", line 20, in __init__
    self.api_key = get_anymail_setting('api_key', esp_name=esp_name, kwargs=kwargs, allow_bare=True)
  File "/usr/local/lib/python3.5/dist-packages/anymail/utils.py", line 381, in get_anymail_setting
    raise AnymailConfigurationError(message)
anymail.exceptions.AnymailConfigurationError: You must set ANYMAIL_MAILGUN_API_KEY or ANYMAIL = {'MAILGUN_API_KEY': ...} or MAILGUN_API_KEY in your Django settings
>>> from django.conf import settings
>>> settings.ANYMAIL
{'MANDRILL_API_KEY': '<redacted>', 'WEBHOOK_SECRET': 'spam:eggs'}
```

pip freeze
```
blinker==1.3
brotlipy==0.7.0
cffi==1.11.5
chardet==2.3.0
cloud-init==18.2
command-not-found==0.3
configobj==5.0.6
croniter==0.3.8
cryptography==1.2.3
defusedxml==0.5.0
Django==2.1b1
django-allauth==0.36.0
django-anymail==3.0
django-nocaptcha-recaptcha==0.1.0
gunicorn==19.8.1
idna==2.0
Jinja2==2.8
jsonpatch==1.10
jsonpointer==1.9
language-selector==0.1
MarkupSafe==0.23
msgpack-python==0.4.6
oauthlib==1.0.3
prettytable==0.7.2
psutil==3.4.2
psycopg2==2.7.5
pyasn1==0.1.9
pycparser==2.18
pycrypto==2.6.1
pycurl==7.43.0
pygobject==3.20.0
PyJWT==1.3.0
pyserial==3.0.1
python-apt==1.1.0b1+ubuntu0.16.4.1
python-dateutil==2.4.2
python-debian==0.1.27
python-systemd==231
python3-openid==3.1.0
pytz==2014.10
PyYAML==3.11
requests==2.9.1
requests-oauthlib==1.0.0
six==1.10.0
ssh-import-id==5.5
tornado==4.2.1
ufw==0.35
unattended-upgrades==0.1
urllib3==1.13.1
whitenoise==3.3.1
```

Python 3.5.2

**Comment by astronouth7303** [comment]
oh, i'm a flippin' idiot. `EMAIL_BACKEND = "anymail.backends.mailgun.EmailBackend"`.
