### ISSUE TITLE
Postmark inbound test email can not be parsed

### ISSUE THREAD

**Issue by Ecno92** [anymail/django-anymail#304]
It seems like the inbound test email from postmark can not be parsed by anymail

After pressing the check button in postmark:

![Screenshot from 2023-04-03 15-34-29](https://user-images.githubusercontent.com/5213399/229525953-edb31c1e-1598-4bf3-ad35-63a5e601197e.png)

- Anymail version: 91.
- ESP: Postmark
- Your ANYMAIL settings (change secrets to "redacted"): According documentation, Work in progress during development..
- Versions of Django, requests, python: python 3.10.6 with Django 4.1.7
- Exact error message and/or stack trace
```
[03/Apr/2023 13:07:04] "POST /redacted/inbound/ HTTP/1.1" 500 104741
Internal Server Error: /redacted/inbound/
Traceback (most recent call last):
  File "/opt/venv/lib/python3.10/site-packages/django/core/handlers/exception.py", line 56, in inner
    response = get_response(request)
  File "/opt/venv/lib/python3.10/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/opt/venv/lib/python3.10/site-packages/django/views/generic/base.py", line 103, in view
    return self.dispatch(request, *args, **kwargs)
  File "/opt/venv/lib/python3.10/site-packages/django/utils/decorators.py", line 46, in _wrapper
    return bound_method(*args, **kwargs)
  File "/opt/venv/lib/python3.10/site-packages/django/views/decorators/csrf.py", line 55, in wrapped_view
    return view_func(*args, **kwargs)
  File "/opt/venv/lib/python3.10/site-packages/anymail/webhooks/base.py", line 67, in dispatch
    return super().dispatch(request, *args, **kwargs)
  File "/opt/venv/lib/python3.10/site-packages/django/views/generic/base.py", line 142, in dispatch
    return handler(request, *args, **kwargs)
  File "/opt/venv/lib/python3.10/site-packages/anymail/webhooks/base.py", line 81, in post
    events = self.parse_events(request)
  File "/opt/venv/lib/python3.10/site-packages/anymail/webhooks/postmark.py", line 26, in parse_events
    return [self.esp_to_anymail_event(esp_event)]
  File "/opt/venv/lib/python3.10/site-packages/anymail/webhooks/postmark.py", line 169, in esp_to_anymail_event
    attachments = [
  File "/opt/venv/lib/python3.10/site-packages/anymail/webhooks/postmark.py", line 172, in <listcomp>
    content=attachment["Content"],
KeyError: 'Content'
```

Some debugging

```
(Pdb) esp_event.get("Attachments", [])
[{'Name': 'test.txt', 'ContentType': 'text/plain', 'Data': 'VGhpcyBpcyBhdHRhY2htZW50IGNvbnRlbnRzLCBiYXNlLTY0IGVuY29kZWQu', 'ContentLength': 45}]
```

I checked the [developer guide by postmark](https://postmarkapp.com/developer/user-guide/inbound/parse-an-email#code-examples) and it seems like anymail is doing the right thing.
The documentation also mentions `Content`, but in my case I'm seeing a `Data` key.

I'll follow up to figure out what's causing this issue. It might be an issue at Postmark, but given that the view crashes as a result of it I'll report it here first.

**Comment by medmunds** [comment]
Thanks for following up with Postmark on this. I reported the same issue to them about a year ago.

Postmark's actual inbound payloads use a `Content` key in attachments (matching their documentation, and Anymail's implementation). But their (hardcoded) sample payload incorrectly uses a `Data` key.

I'm thinking Anymail should maybe allow either key, just in case it takes a while for them to release a fix.

**Comment by Ecno92** [comment]
That puts things in a different perspective. I just had contact with them and they will keep me informed about any fix. 
They do not expect it very soon, because there is a workaround available. 
You can just send a real email to get a correct POST to your endpoint. 

I will continue testing with real data tomorrow. This will allow me to understand how the current implementation works and finish the implementation for my client.

Normally I would not be in favor of workarounds like this, but given that it might take "another year" I think it is not a bad idea to implement.

I'll try to come back to this by the end of this week whether I can pick this up.
