### ISSUE TITLE
Misleading error with fail_silently: "boto3 sesv2 client does not have method 'send_email'"

### ISSUE THREAD

**Issue by technolingo** [anymail/django-anymail#308]
Reporting an error? It's helpful to know:

- Anymail version: `django-anymail[amazon_ses]==9.1`
- ESP: `SES`
- Your ANYMAIL settings
```
EMAIL_BACKEND = "anymail.backends.amazon_sesv2.EmailBackend"
```

- Versions of Django, requests, python
```
Python==3.10.10
Django==4.0.10
requests==2.28.2
boto3==1.26.113
```

- Exact error message and/or stack trace
```
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/gunicorn/workers/sync.py", line 136, in handle
    self.handle_request(listener, req, client, addr)
  File "/usr/local/lib/python3.10/site-packages/gunicorn/workers/sync.py", line 179, in handle_request
    respiter = self.wsgi(environ, resp.start_response)
  File "/usr/local/lib/python3.10/site-packages/django/core/handlers/wsgi.py", line 132, in __call__
    response = self.get_response(request)
  File "/usr/local/lib/python3.10/site-packages/django/core/handlers/base.py", line 140, in get_response
    response = self._middleware_chain(request)
  File "/usr/local/lib/python3.10/site-packages/django/core/handlers/exception.py", line 58, in inner
    response = response_for_exception(request, exc)
  File "/usr/local/lib/python3.10/site-packages/django/core/handlers/exception.py", line 143, in response_for_exception
    log_response(
  File "/usr/local/lib/python3.10/site-packages/django/utils/log.py", line 241, in log_response
    getattr(logger, level)(
  File "/usr/local/lib/python3.10/logging/__init__.py", line 1506, in error
    self._log(ERROR, msg, args, **kwargs)
  File "/usr/local/lib/python3.10/logging/__init__.py", line 1624, in _log
    self.handle(record)
  File "/usr/local/lib/python3.10/logging/__init__.py", line 1634, in handle
    self.callHandlers(record)
  File "/usr/local/lib/python3.10/logging/__init__.py", line 1696, in callHandlers
    hdlr.handle(record)
  File "/usr/local/lib/python3.10/logging/__init__.py", line 968, in handle
    self.emit(record)
  File "/usr/local/lib/python3.10/site-packages/django/utils/log.py", line 128, in emit
    self.send_mail(subject, message, fail_silently=True, html_message=html_message)
  File "/usr/local/lib/python3.10/site-packages/django/utils/log.py", line 131, in send_mail
    mail.mail_admins(
  File "/usr/local/lib/python3.10/site-packages/django/core/mail/__init__.py", line 134, in mail_admins
    mail.send(fail_silently=fail_silently)
  File "/usr/local/lib/python3.10/site-packages/django/core/mail/message.py", line 298, in send
    return self.get_connection(fail_silently).send_messages([self])
  File "/usr/local/lib/python3.10/site-packages/anymail/backends/base.py", line 114, in send_messages
    sent = self._send(message)
  File "/usr/local/lib/python3.10/site-packages/anymail/backends/base.py", line 144, in _send
    response = self.post_to_esp(payload, message)
  File "/usr/local/lib/python3.10/site-packages/anymail/backends/amazon_sesv2.py", line 91, in post_to_esp
    raise NotImplementedError(
NotImplementedError: boto3 sesv2 client does not have method 'send_email'. Check AmazonSESV2SendEmailPayload.api_name.
```

- Any other relevant code and settings (e.g., for problems
  sending, your code that sends the message)
None

**Comment by medmunds** [comment]
Thanks for the report, and for including the whole stack trace (which was essential to figure out what's going on here).

This seems to be a combination of some problems in your code or environment, plus an Anymail bug that results in misleading error messages.

First, the problems on your end:

1. Whatever request you made to your Django server failed, with an unexpected exception. Your server is trying to respond with a 500 error.
2. Your Django logging is set up to `mail_admins` to let you know about the problem. But Anymail was unable to successfully create a boto3 sesv2 client to send that mail. The most likely explanation is boto3 can't find the necessary [credentials](https://boto3.amazonaws.com/v1/documentation/api/latest/guide/configuration.html#configuring-credentials), though there could be other causes. (Have you successfully sent any email from this server?)

Django logging sends the email with `fail_silently=True`, so the correct behavior would be for Anymail to just ignore the configuration problems and not send any email. (And then you would hopefully discover problem 1 above in your log files.)

The Anymail bug is in the SESv2 backend: it should not be trying to post_to_esp if boto3 client creation failed and fail_silently is enabled. The "boto3 sesv2 client does not have method" error message is misleading: the actual problem is there is no client, and we should just ignore that if asked to fail_silently.

I'll fix the Anymail bug. In the meantime, I'd suggest either fixing your server settings so that Anymail is able to successfully send email through SES, or removing `mail_admins` from your Django logging config (if you don't want to receive email about errors).

**Comment by technolingo** [comment]
Hi @medmunds ,

Thank you very much for your prompt and detailed response!
Indeed, I had misconfigured the boto3 environment variables.  Now the issue is resolved.

Best
