### ISSUE TITLE
Mailjet ESP response 429 not as JSON

### ISSUE THREAD

**Issue by rodrigondec** [anymail/django-anymail#409]
# Intro
The MailJet ESP does not return a JSON data on responses of type 429!

Because of this, the code in `anymail.backends.base_requests.AnymailRequestsBackend.deserialize_json_response` breaks with a JSONDecodeError.

Can anymail support a HTML response? Or this erros should be "handled" and translated to a "global error" with a valid dict?

# Infos

- Anymail version: 12.0
- ESP (Mailgun, SendGrid, etc.): MailJet
- Your ANYMAIL settings (change secrets to "redacted"): 
```
ANYMAIL = {
    "MAILJET_API_KEY": config("MAILJET_API_KEY"),
    "MAILJET_SECRET_KEY": config("MAILJET_SECRET_KEY"),
    "SEND_DEFAULTS": {
        "track_opens": True,
        "track_clicks": True,
    },
}
```
- Versions of Django, requests, python: Django 4.0, requests 2.32.3, python 3.9.
- Exact error message and/or stack trace: 
```
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/requests/models.py", line 974, in json
    return complexjson.loads(self.text, **kwargs)
  File "/usr/local/lib/python3.9/json/__init__.py", line 346, in loads
    return _default_decoder.decode(s)
  File "/usr/local/lib/python3.9/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/local/lib/python3.9/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/anymail/backends/base_requests.py", line 129, in deserialize_json_response
    return response.json()
  File "/usr/local/lib/python3.9/site-packages/requests/models.py", line 978, in json
    raise RequestsJSONDecodeError(e.msg, e.doc, e.pos)
requests.exceptions.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/app_user/external_services/notifications/email.py", line 225, in _send_email
    sent_emails_count = message.send()
  File "/usr/local/lib/python3.9/site-packages/django/core/mail/message.py", line 298, in send
    return self.get_connection(fail_silently).send_messages([self])
  File "/usr/local/lib/python3.9/site-packages/anymail/backends/base.py", line 114, in send_messages
    sent = self._send(message)
  File "/usr/local/lib/python3.9/site-packages/anymail/backends/base_requests.py", line 51, in _send
    return super()._send(message)
  File "/usr/local/lib/python3.9/site-packages/anymail/backends/base.py", line 147, in _send
    recipient_status = self.parse_recipient_status(response, payload, message)
  File "/usr/local/lib/python3.9/site-packages/anymail/backends/mailjet.py", line 44, in parse_recipient_status
    parsed_response = self.deserialize_json_response(response, payload, message)
  File "/usr/local/lib/python3.9/site-packages/anymail/backends/base_requests.py", line 131, in deserialize_json_response
    raise AnymailRequestsAPIError(
anymail.exceptions.AnymailRequestsAPIError: Invalid JSON in Mailjet API response
requests.exceptions.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
Mailjet API response 429 (Too Many Requests): '<html><body><h1>429 Too Many Requests</h1></body></html>''
```
- Any other relevant code and settings (e.g., for problems  sending, your code that sends the message): None

**Comment by medmunds** [comment]
Thanks for the report. The correct behavior here would be an AnymailRequestsAPIError.

The bug is that Anymail's Mailjet backend assumes all 4xx responses will have JSON data, in [mailjet.EmailBackend.raise_for_status()](https://github.com/anymail/django-anymail/blob/45848440b3727d8236bdae8c4b2b081705d66f7a/anymail/backends/mailjet.py#L37-L40). We should be able to fix that by also verifying the response's content type is application/json, and chaining to the superclass (which raises the correct error) otherwise.

**Comment by rodrigondec** [comment]
Until the correct FIX, I'm overwriting the MailJet EmailBackend like so:

```python

from anymail.backends.mailjet import EmailBackend


class IncomeMailjetEmailBackend(EmailBackend):
    def deserialize_json_response(self, response, payload, message):
        if response.status_code == 429:
            return {
                "ErrorCode": "429",
            }
        return super().deserialize_json_response(
            response=response, payload=payload, message=message
        )


``` 

As per this line, this is a "appropriate monkey patching" https://github.com/anymail/django-anymail/blob/45848440b3727d8236bdae8c4b2b081705d66f7a/anymail/backends/mailjet.py#L43-L51

**Comment by medmunds** [comment]
> Until the FIX, I'm overwriting the MailJet EmailBackend like so: ...

Yep, that ought to give you exactly the same AnymailRequestsAPIError as after the fix.
