### ISSUE TITLE
Inbound email receiver returns AnymailInvalidAddress error on Heroku + Python 2.7

### ISSUE THREAD

**Issue by rnevius** [anymail/django-anymail#98]
## Project Info:
-  Anymail 2.0
-  ESP: Mailgun
-  Django 1.8
-  Python 2.7.14
-  Heroku host

## Stack Trace:
```
Internal Server Error: /admin/messages/webhooks/mailgun/inbound/
Traceback (most recent call last):
  File "/app/.heroku/python/lib/python2.7/site-packages/django/core/handlers/base.py", line 132, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/app/.heroku/python/lib/python2.7/site-packages/django/views/generic/base.py", line 71, in view
    return self.dispatch(request, *args, **kwargs)
  File "/app/.heroku/python/lib/python2.7/site-packages/django/utils/decorators.py", line 34, in _wrapper
    return bound_func(*args, **kwargs)
  File "/app/.heroku/python/lib/python2.7/site-packages/django/views/decorators/csrf.py", line 58, in wrapped_view
    return view_func(*args, **kwargs)
  File "/app/.heroku/python/lib/python2.7/site-packages/django/utils/decorators.py", line 30, in bound_func
    return func.__get__(self, type(self))(*args2, **kwargs2)
  File "/app/.heroku/python/lib/python2.7/site-packages/anymail/webhooks/base.py", line 109, in dispatch
    return super(AnymailBaseWebhookView, self).dispatch(request, *args, **kwargs)
  File "/app/.heroku/python/lib/python2.7/site-packages/django/views/generic/base.py", line 89, in dispatch
    return handler(request, *args, **kwargs)
  File "/app/.heroku/python/lib/python2.7/site-packages/anymail/webhooks/base.py", line 126, in post
    self.signal.send(sender=self.__class__, event=event, esp_name=esp_name)
  File "/app/.heroku/python/lib/python2.7/site-packages/django/dispatch/dispatcher.py", line 201, in send
    response = receiver(signal=self, sender=sender, **named)
  File "/app/./urban_site/messages/views.py", line 84, in handle_inbound
    [agent.email]
  File "/app/.heroku/python/lib/python2.7/site-packages/django/core/mail/__init__.py", line 62, in send_mail
    return mail.send()
  File "/app/.heroku/python/lib/python2.7/site-packages/django/core/mail/message.py", line 303, in send
    return self.get_connection(fail_silently).send_messages([self])
  File "/app/.heroku/python/lib/python2.7/site-packages/anymail/backends/base.py", line 90, in send_messages
    sent = self._send(message)
  File "/app/.heroku/python/lib/python2.7/site-packages/anymail/backends/base_requests.py", line 58, in _send
    return super(AnymailRequestsBackend, self)._send(message)
  File "/app/.heroku/python/lib/python2.7/site-packages/anymail/backends/base.py", line 119, in _send
    payload = self.build_message_payload(message, self.send_defaults)
  File "/app/.heroku/python/lib/python2.7/site-packages/anymail/backends/mailgun.py", line 30, in build_message_payload
    return MailgunPayload(message, defaults, self)
  File "/app/.heroku/python/lib/python2.7/site-packages/anymail/backends/mailgun.py", line 71, in __init__
    super(MailgunPayload, self).__init__(message, defaults, backend, auth=auth, *args, **kwargs)
  File "/app/.heroku/python/lib/python2.7/site-packages/anymail/backends/base_requests.py", line 119, in __init__
    super(RequestsPayload, self).__init__(message, defaults, backend)
  File "/app/.heroku/python/lib/python2.7/site-packages/anymail/backends/base.py", line 268, in __init__
    value = converter(value)
  File "/app/.heroku/python/lib/python2.7/site-packages/anymail/utils.py", line 158, in parse_address_list
    raise AnymailInvalidAddress(errmsg)
AnymailInvalidAddress: Invalid email address '' parsed from ''.
```

## Relevant Code:
```
@receiver(inbound)
def handle_inbound(sender, event, esp_name, **kwargs):
    message = event.message
    from_email = message.from_email.addr_spec
```

I suspect this is an issue with parsing `addr_spec`, as doing `print(message.from_email)` returns a valid email in the form: `First Last <firstlast@outlook.com>` (also occurs from Gmail addresses). This issue doesn't occur when using ngrok locally.

**Comment by medmunds** [comment]
Thanks for including the stack trace. It looks like like your inbound receiver is trying to send a new message, and the AnymailInvalidAddress error is coming from that send:

```
  File "/app/./urban_site/messages/views.py", line 84, in handle_inbound
    [agent.email]
  File "/app/.heroku/python/lib/python2.7/site-packages/django/core/mail/__init__.py", line 62, in send_mail
    return mail.send()
```

It would help to see the handle_inbound code that's constructing and sending the new message. (Just to double check, are you sure `agent.email` is valid? Because something like `to=['']` would also result in the error you're seeing.)

If you're saying that `str(message.from_email)` returns `'First Last <firstlast@outlook.com>'` but `message.from_email.addr_spec` returns `''` on the same inbound message, that's definitely a bug. If so, I'm guessing from_email is more complicated than the example you gave, because that specific address should work fine:

```python
>>> from anymail.utils import parse_address_list
>>> from_email = parse_address_list(['First Last <firstlast@outlook.com>'])[0]
>>> str(from_email)
'First Last <firstlast@outlook.com>'
>>> from_email.addr_spec
u'firstlast@outlook.com'
```

I just fixed a [couple](https://github.com/anymail/django-anymail/commit/70094cf3bc63e19d1e427e52918e49117e843573) of [bugs](https://github.com/anymail/django-anymail/commit/3d27e3fe6b81c40659c8143a142918531098766f) around Python 2.7 inbound header parsing, which could apply. Looking at the raw event from Mailgun, available as `event.esp_event` in your receiver, might provide some more clues.

**Comment by rnevius** [comment]
Thanks for the detailed reply. I somehow missed that line of the stack trace when I read it the first 10 times 😄. While I haven't changed any code, I'm no longer seeing the issue. It looks like the problem may have been due to a delayed scheduled job in my app code. Closing this one!
